package domain;
// Generated Oct 4, 2020 8:30:14 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Contact generated by hbm2java
 */
@Entity
@Table(name="Contact"
    ,catalog="FashionBlog"
)
public class Contact  implements java.io.Serializable {


     private int commentId;
     private String name;
     private String email;
     private String message;

    public Contact() {
    }

    public Contact(int commentId, String name, String email, String message) {
       this.commentId = commentId;
       this.name = name;
       this.email = email;
       this.message = message;
    }
   
     @Id 

    
    @Column(name="CommentID", unique=true, nullable=false)
    public int getCommentId() {
        return this.commentId;
    }
    
    public void setCommentId(int commentId) {
        this.commentId = commentId;
    }

    
    @Column(name="Name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="Email", nullable=false)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="Message", nullable=false)
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }




}


